FROM rust:1.64.0-alpine3.16

RUN apk add --no-cache musl-dev bash jq make
RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/community upx

WORKDIR /app

ADD Cargo.lock Cargo.toml /app

RUN mkdir scripts src vendor
ADD vendor /app/vendor
ADD src /app/src
ADD scripts /app/scripts

ENTRYPOINT bash
